//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multimodal_Learning_Analytics_for_Sustained_Attention.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENABLE_DIAGNOSTICS {
            get {
                return ((bool)(this["ENABLE_DIAGNOSTICS"]));
            }
            set {
                this["ENABLE_DIAGNOSTICS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public int VIDEO_WIDTH {
            get {
                return ((int)(this["VIDEO_WIDTH"]));
            }
            set {
                this["VIDEO_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int VIDEO_HEIGHT {
            get {
                return ((int)(this["VIDEO_HEIGHT"]));
            }
            set {
                this["VIDEO_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int VIDEO_FRAMERATE {
            get {
                return ((int)(this["VIDEO_FRAMERATE"]));
            }
            set {
                this["VIDEO_FRAMERATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\psi_stores")]
        public string PSI_STORES_FOLDER {
            get {
                return ((string)(this["PSI_STORES_FOLDER"]));
            }
            set {
                this["PSI_STORES_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\research_project")]
        public string EXPERIMENTS_TEXTS_BASE_FOLDER {
            get {
                return ((string)(this["EXPERIMENTS_TEXTS_BASE_FOLDER"]));
            }
            set {
                this["EXPERIMENTS_TEXTS_BASE_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\experiment_results\\experiment1")]
        public string EXPERIMENT1_RESULTS_FOLDER {
            get {
                return ((string)(this["EXPERIMENT1_RESULTS_FOLDER"]));
            }
            set {
                this["EXPERIMENT1_RESULTS_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.137.1:12345")]
        public string LAV_AUDIO_SUB_IP {
            get {
                return ((string)(this["LAV_AUDIO_SUB_IP"]));
            }
            set {
                this["LAV_AUDIO_SUB_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav-audio-raw")]
        public string LAV_RAW_TOPIC {
            get {
                return ((string)(this["LAV_RAW_TOPIC"]));
            }
            set {
                this["LAV_RAW_TOPIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lav-audio-freq")]
        public string LAV_FREQ_TOPIC {
            get {
                return ((string)(this["LAV_FREQ_TOPIC"]));
            }
            set {
                this["LAV_FREQ_TOPIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LAV_SYNC_TIME {
            get {
                return ((bool)(this["LAV_SYNC_TIME"]));
            }
            set {
                this["LAV_SYNC_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1:12345")]
        public string EP_AUDIO_SUB_IP {
            get {
                return ((string)(this["EP_AUDIO_SUB_IP"]));
            }
            set {
                this["EP_AUDIO_SUB_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ep-audio-raw")]
        public string EP_RAW_TOPIC {
            get {
                return ((string)(this["EP_RAW_TOPIC"]));
            }
            set {
                this["EP_RAW_TOPIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ep-audio-freq")]
        public string EP_FREQ_TOPIC {
            get {
                return ((string)(this["EP_FREQ_TOPIC"]));
            }
            set {
                this["EP_FREQ_TOPIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EP_SYNC_TIME {
            get {
                return ((bool)(this["EP_SYNC_TIME"]));
            }
            set {
                this["EP_SYNC_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sound-played")]
        public string AUDIO_PLAYER_TOPIC {
            get {
                return ((string)(this["AUDIO_PLAYER_TOPIC"]));
            }
            set {
                this["AUDIO_PLAYER_TOPIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.137.1:12347")]
        public string AUDIO_PLAYER_SUB_IP {
            get {
                return ((string)(this["AUDIO_PLAYER_SUB_IP"]));
            }
            set {
                this["AUDIO_PLAYER_SUB_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string IR_COM_PORT {
            get {
                return ((string)(this["IR_COM_PORT"]));
            }
            set {
                this["IR_COM_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public int IR_BAUD_RATE {
            get {
                return ((int)(this["IR_BAUD_RATE"]));
            }
            set {
                this["IR_BAUD_RATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VIDEO_VERTICAL_FLIP {
            get {
                return ((bool)(this["VIDEO_VERTICAL_FLIP"]));
            }
            set {
                this["VIDEO_VERTICAL_FLIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4410")]
        public int AUDIO_BLOCK_SIZE {
            get {
                return ((int)(this["AUDIO_BLOCK_SIZE"]));
            }
            set {
                this["AUDIO_BLOCK_SIZE"] = value;
            }
        }
    }
}
